// react-toutou/src/components/items/multiple-pic/index.js
/**
 * @file entry file
 * @author shaw
 */

import React, {Component} from 'react';
import {itemFy, clickAble} from '../decorators';
import style from './style.css';

@itemFy(true)
export default class MultiplePic extends Component {

	static classes = 'multiple-pic';

	render() {

		const {title, imageList} = this.props.data;

		const imageComponents = imageList.map(image => (<img src={image} />));

		return (<React.Fragment>
				<h3>{title}</h3>
				{imageComponents}
			</React.Fragment>);
	}
}

// vue-toutou/src/components/items/multiple-pic.vue
<template>
    <div class="item multiple-image" v-on:click="skip">
        <h3>
            {{title}}
        </h3>
        <div class="image-list">
            <img v-for="image in imageList" v-bind:src="image"/>
        </div>
    </div>
</template>

<script>
import BaseOptions from './base.js';
/**
 * @file feed流多图item
 * @suthor shaw
 */
export default {
    extends: BaseOptions
}
</script>

<style scoped>
@import "./index.css";

.item.multiple-image h3 {
    font-size: 17px;
}

.item.multiple-image .image-list img {
    width: 33%;
}            
</style>
